version: '3.1'

networks:
  web:
    external: true
  media:
    external:
      name: media-containers

services:

  transmission:
    container_name: Transmission
    image: haugene/transmission-openvpn
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    networks:
      - media
    environment:
      - TZ=America/Chicago
      - OPENVPN_PROVIDER=XXXX
      - OPENVPN_CONFIG=XXXX
      - OPENVPN_USERNAME=XXXX
      - OPENVPN_PASSWORD=XXXX
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=XXXX
      - LOCAL_NETWORK=x.x.x.x/24
      - TRANSMISSION_HOME=/config
      - TRANSMISSION_DOWNLOAD_DIR=/data/complete
      - TRANSMISSION_INCOMPLETE_DIR=/data/incomplete
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
      - TRANSMISSION_WATCH_DIR=/data/watch
      - PUID=XXXX
      - PGID=XXXX
    dns:
      - 1.1.1.1
    ports:
      - 9091:9091
    volumes:
      - /docker/volumes/transmission/config:/config
      - /nas/terastation/Downloads/:/data
      - /etc/localtime:/etc/localtime:ro

  plex:
    container_name: Plex
    image: plexinc/pms-docker:beta
    restart: unless-stopped
    networks:
      - media
    environment:
      - TZ=America/Chicago
      - PLEX_CLAIM=XXXX
      - PLEX_UID=XXXX
      - PLEX_GID=XXXX
      - ADVERTISE_IP=http://x.x.x.x:32400/
    hostname: Plex
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - /run
      - /docker/volumes/plex/config:/config
      - /docker/volumes/plex/transcode:/transcode
      - /nas/terastation/Media:/srv/media
      - /nas/terastation/Downloads:/srv/torrents

  ombi:
    container_name: Ombi
    image: rogueosb/ombi
    restart: unless-stopped
    networks:
      - web
      - media
    environment:
      - TZ=America/Chicago
      - PUID=XXXX
      - PGID=XXXX
    expose:
      - 3579
    volumes:
      - /docker/volumes/ombi:/config

  sonarr:
    container_name: Sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    networks:
      - media
    ports:
      - 8989:8989
    #depends_on:
    #  - transmission
    environment:
      - TZ=America/Chicago
      - PUID=XXXX
      - PGID=XXXX
    volumes:
      - /docker/volumes/sonarr:/config
      - /nas/terastation/Media/animu/show:/anime
      - /nas/terastation/Media/shows:/tv
      - /nas/terastation/Downloads/complete:/downloads
      - /nas/terastation/Downloads:/data

  radarr:
    container_name: Radarr
    image: linuxserver/radarr
    restart: unless-stopped
    networks:
      - media
    ports:
      - 7878:7878
    #depends_on:
    #  - transmission
    environment:
      - TZ=America/Chicago
      - PUID=XXXX
      - PGID=XXXX
    volumes:
      - /docker/volumes/radarr:/config
      - /nas/terastation/Media/movies:/movies
      - /nas/terastation/Downloads/complete:/downloads
      - /nas/terastation/Downloads:/data

  jackett:
    image: linuxserver/jackett
    container_name: Jackett
    restart: always
    networks:
      - media
    environment:
      - PGID=XXXX
      - PUID=XXXX
      - TZ=America/Chicago
    volumes:
      - /docker/volumes/jackett/config:/config
      - /nas/terastation/Downloads/complete:/downloads
    ports:
      - 9117:9117
